### ISSUE TITLE
AmazonChimeSDKMachineLearning XCFramework not downloading

### ISSUE THREAD

**Issue by notapplicableio** [aws/amazon-chime-sdk-ios-spm#5]
Package loading has stopped working for me.

The URL seems fine for each.

[~]$ curl --head https://amazon-chime-sdk-ios.s3.amazonaws.com/sdk-without-bitcode/0.23.1/spm/AmazonChimeSDK-0.23.1.zip
HTTP/1.1 200 OK
x-amz-id-2: STcLZYvwPedq/eQMxDLWqQtSQzhFPDckMnj6JBols68mTqH6wZXxfNA19HjouvE1qwyQcbFs2uA=
x-amz-request-id: 4ZC0RTYB3HJA8BDD
Date: Sun, 25 Jun 2023 23:15:54 GMT
Last-Modified: Thu, 18 May 2023 23:49:34 GMT
ETag: "9f404e5dd0fb78201e183fd8fc3c4897"
x-amz-server-side-encryption: AES256
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Server: AmazonS3
Content-Length: 2373000

[~]$ curl --head https://amazon-chime-sdk-ios.s3.amazonaws.com/media-without-bitcode/0.18.1/spm/AmazonChimeSDKMedia-0.18.1.zip      
HTTP/1.1 200 OK
x-amz-id-2: UUotjWFf9Wqnlms7U4SFxOBHUx0LG2KihVSxAj3FuObr1jI+YE+8yesGXRvfZ5tQYwYzyWU9mhQ=
x-amz-request-id: 0TE2SSF24S21QSWA
Date: Sun, 25 Jun 2023 23:17:01 GMT
Last-Modified: Thu, 18 May 2023 23:48:16 GMT
ETag: "3b229713c3600f81e4c7bf8b732e2046"
x-amz-server-side-encryption: AES256
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Server: AmazonS3
Content-Length: 17515581

[~]$ curl --head https://amazon-chime-sdk-ios.s3.amazonaws.com/machine-learning-without-bitcode/0.2.0/spm/AmazonChimeSDKMachineLearning-0.2.0.zip
HTTP/1.1 200 OK
x-amz-id-2: d763S8IQX7l8FfyfPsT5wn/LCyj2xz5dUgGp0xakDERKclzCJRytPkDsNcV1/tY7RJznYbHIitw=
x-amz-request-id: CBKCMYVXQ0H577WD
Date: Sun, 25 Jun 2023 23:17:45 GMT
Last-Modified: Fri, 23 Jun 2023 22:18:46 GMT
ETag: "09442f479f80b58dd0ee8a483372ffb4"
x-amz-server-side-encryption: AES256
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Server: AmazonS3
Content-Length: 106170

The content length for AmazonChimeSDKMachineLearning seems small.

And when I download directly I get this.

<img width="580" alt="Screenshot 2023-06-26 at 11 21 40 am" src="https://github.com/aws/amazon-chime-sdk-ios-spm/assets/57690/72761122-2763-40f4-9996-a33361923c4f">

This is reflected in Xcode where package loading breaks.

**Comment by notapplicableio** [comment]
CCing you @georgezy-amzn to get your attention :)

**Comment by oliverfoggin** [comment]
Today we started to get an issue with our CI when fetching AMSChime SDK... 
![image](https://github.com/aws/amazon-chime-sdk-ios-spm/assets/1813244/43135f49-1603-46de-b0ed-2658931e496e)

It seems suspiciously related to this.

**Comment by yochum** [comment]
Thank you @oliverfoggin & @notapplicableio. We are working to resolve the error with the release. We will update you here when resolved.

**Comment by georgezy-amzn** [comment]
Hi all, sorry for the inconvenience. We have recovered the binary, and verified. Could you also verify?

**Comment by notapplicableio** [comment]
LGTM

Can you add a section to the readme for using SPM. It's a bit obscure/hidden at the moment. The more people that use SPM the sooner we can be alerted to problems. :)

Thanks for fixing.
